<?xml version="1.0"?>
<robot>
  <property name="M_PI" value="3.14159"/>
  <property name="M_SCALE" value="0.01"/>
  <property name="BASE_RADIUS" value="0.18"/>
  <property name="BASE_HEIGHT" value="0.05"/>
  <property name="BASE_MASS" value="20"/>
  
  <macro name="robotino_body">
    
  	<link name="base_link">
      <inertial>
        <mass value="${BASE_MASS}" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>
      <visual>
        <origin xyz="0.01 0 0" rpy="0 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://my_robotino_urdf/meshes/RobotinoBody.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${BASE_HEIGHT/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${BASE_RADIUS}" length="${BASE_HEIGHT}"/>
        </geometry>
      </collision>
    </link>
    
    <wheel name="wheel0" parent="base_link">
      <origin xyz="0.065 0.11 0.04" rpy="0 0 ${M_PI/3}"/>
      <axis xyz="-1 0 0"/>
    </wheel>
    <wheel name="wheel1" parent="base_link">
      <origin xyz="-0.13 0 0.04" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </wheel>
    <wheel name="wheel2" parent="base_link">
      <origin xyz="0.065 -0.11 0.04" rpy="0 0 -${M_PI/3}"/>
      <axis xyz="-1 0 0"/>
    </wheel>
    
    <command_bridge name="command_bridge" parent="base_link">
      <origin xyz="-0.05 0 0.13" rpy="0 0 ${M_PI/2}"/>
    </command_bridge>
    
    <camera name="camera" parent="base_link">
      <origin xyz="0.144 0 0.07" rpy="0 0 0"/>
    </camera>
    
    <anglebracketusb name="anglebracketusb" parent="base_link">
      <origin xyz="0.008 0 0.137" rpy="0 0 ${M_PI/2}"/>
    </anglebracketusb>
    
    <!--laser name="laser" parent="base_link">
      <origin xyz="-0.022 0 0.232" rpy="0 0 0"/>
    </laser-->
    
    <laser name="laser" parent="base_link">
      <origin xyz="0.155 0 ${BASE_HEIGHT/2}" rpy="0 0 0"/>
    </laser>

    <laser name="laser1" parent="base_link">
      <origin xyz="0.11873 0.09963 ${BASE_HEIGHT/2}" rpy="0 0 ${M_PI/4.5}"/>
    </laser>

    <laser name="laser2" parent="base_link">
      <origin xyz="0.11873 -0.099630 ${BASE_HEIGHT/2}" rpy="0 0 -${M_PI/4.5}"/>
    </laser>

    <laser name="laser3" parent="base_link">
      <origin xyz="0.02691 0.15264 ${BASE_HEIGHT/2}" rpy="0 0 ${M_PI/2.25}"/>
    </laser>

    <laser name="laser4" parent="base_link">
      <origin xyz="0.02691 -0.15264 ${BASE_HEIGHT/2}" rpy="0 0 -${M_PI/2.25}"/>
    </laser>

    <laser name="laser5" parent="base_link">
      <origin xyz="-0.0775 0.13423 ${BASE_HEIGHT/2}" rpy="0 0 ${M_PI/1.5}"/>
    </laser>

    <laser name="laser6" parent="base_link">
      <origin xyz="-0.0775 -0.13423 ${BASE_HEIGHT/2}" rpy="0 0 -${M_PI/1.5}"/>
    </laser>

    <laser name="laser7" parent="base_link">
      <origin xyz="-0.14565 0.05301 ${BASE_HEIGHT/2}" rpy="0 0 ${M_PI/1.125}"/>
    </laser>

    <laser name="laser8" parent="base_link">
      <origin xyz="-0.14565 -0.05301 ${BASE_HEIGHT/2}" rpy="0 0 -${M_PI/1.125}"/>
    </laser>

  </macro>
</robot>
